// <auto-generated />
namespace UFX_WCCI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class usernameLogin_BioFixes_PhotoUplaod : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(usernameLogin_BioFixes_PhotoUplaod));
        
        string IMigrationMetadata.Id
        {
            get { return "201608191513494_usernameLogin_BioFixes_PhotoUplaod"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
